### ISSUE TITLE
clock_setup() bug, and a question on SDRAM initialization for the kernel

### ISSUE THREAD

**Issue by henrychoi** [mcoquelin-stm32/afboot-stm32#1]
I believe clock_setup(void) has a bug.  A copy and paste of my git commit (not pushed to master):
-       *RCC_CFGR &= ~RCC_CFGR_SW_MASK;
-       *RCC_CFGR &= ~RCC_CFGR_SW_MASK;//Change system clock source and wait

I also have a question on the use of the external SDRAM, which is enabled: where is the code that copies the kernel .text from flash to the SDRAM and zeros out the kernel .bss in the SDRAM before calling the kernel entry function (with 0x08004000 as the 2nd kernel argument to the kernel)?

**Comment by mcoquelin-stm32** [comment]
Hi Henry,

About the clock bug, I am not sure to understand what you mean.
The lines are printed two times, and the second one with just a comment.
Could you please explain me what is wrong?

About SD-Ram, the .text is executed from Flash, so an XipImage has to be generated.
For Kernel's BSS section, the kernel manages to clear during in its early init, see __mmap_switched function in arch/arm/kenrel/head-common.S.

Regards,
Maxime

**Comment by henrychoi** [comment]
Hi Maxime I was in a hurry sorry about the imprecise comment.  When you
chceck for pll ready you have to check that the bit is not set in the
infinite while loop.

Also I know about the xip.  I meant the .data section which has to be
copies to the RAM.  How do you know where to copy from and to?

**Comment by henrychoi** [comment]
Hopefully this is clearer Maxime.

 static void clock_setup(void)
 {
- ```
    // Function roughly follows Emcraft u-boot
  ```
  
  cpu/arm_cortexm3/stm32/clock.c
      volatile uint32_t *RCC_CR = (void *)(RCC_BASE + 0x00);
      volatile uint32_t *RCC_PLLCFGR = (void *)(RCC_BASE + 0x04);
      volatile uint32_t *RCC_CFGR = (void *)(RCC_BASE + 0x08);
  @@ -54,12 +66,13 @@ static void clock_setup(void)
      *RCC_PLLCFGR = val;
  
  ```
  *RCC_CR |= RCC_CR_PLLON;
  ```
-       while (*RCC_CR & RCC_CR_PLLRDY) {
-       while (!(*RCC_CR & RCC_CR_PLLRDY)) { //wait for PLL lock
      }

As for the location of the .data section, I understand now that you are
saying it should also be in the flash (execute in place), and should be
copied by the Linux during early startup phase.  It's just that with the
Buildroot toolchain I compiled (gcc 5.2 eabihf), the .data section winds up
at the SDRAM as you can see from the output of my readelf:

Section Headers:

  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk
Inf Al

  [ 0]                   NULL            00000000 000000 000000 00      0
0  0

  [ 1] .head.text        PROGBITS        08008000 008000 000060 00  AX  0
0  4

  [ 2] .text             PROGBITS        08008060 008060 0b4ad0 00  AX  0
0 32

...

  [15] .data             PROGBITS        90008000 118000 00c9a0 00  WA  0
0 512

  [16] .bss              NOBITS          900149a0 1249a0 018900 00  WA  0
0 32

Sorry for asking so many questions.  I'll just try to figure it out on my
own.  Thanks for your contribution on the Cortex M4 Maxime!

On Wed, Jan 13, 2016 at 6:10 AM, Henry Choi henry.omd@gmail.com wrote:

> Hi Maxime I was in a hurry sorry about the imprecise comment.  When you
> chceck for pll ready you have to check that the bit is not set in the
> infinite while loop.
> 
> Also I know about the xip.  I meant the .data section which has to be
> copies to the RAM.  How do you know where to copy from and to?
> On Jan 13, 2016 2:58 AM, "mcoquelin-stm32" notifications@github.com
> wrote:
> 
> > Hi Henry,
> > 
> > About the clock bug, I am not sure to understand what you mean.
> > The lines are printed two times, and the second one with just a comment.
> > Could you please explain me what is wrong?
> > 
> > About SD-Ram, the .text is executed from Flash, so an XipImage has to be
> > generated.
> > For Kernel's BSS section, the kernel manages to clear during in its early
> > init, see __mmap_switched function in arch/arm/kenrel/head-common.S.
> > 
> > Regards,
> > Maxime
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mcoquelin-stm32/afboot-stm32/issues/1#issuecomment-171254219
> > .

**Comment by mcoquelin-stm32** [comment]
Hi Henry,
Thanks for the clarification, this is very clear now.
You are right PLLRDY bit is set as soon as PLL is ready, so it didn't wait for the PLL to be locked.
Thanks a lot for the report, I will fix this as soon as possible.

For the data section, I think its address is good in the elf file (vmllinux), as this is where the data are copied during early boot. In case of xip image, the data are placed in Flash in __data_loc.
And we can see it is copied to _sdata in __mmap_switched:

```
cmp r4, r5              @ Copy data segment if needed
```

1:  cmpne   r5, r6
    ldrne   fp, [r4], #4
    strne   fp, [r5], #4
    bne 1b

Hope it clarifies a bit!

Kind regards,
Maxime

**Comment by mcoquelin-stm32** [comment]
Patch pushed to master branch, thanks for your contribution.

Can I close the issue now, or you have other questions?
Regards,
Maxime

**Comment by henrychoi** [comment]
Thank you so much for pushing the fix, and for the startup code explanation
Maxime.  Yes you can close the issue please.  I am not sure if you are also
interested in the XIP startup issue, so I should offline the XIP startup
discussion, but I don't know how else to reach you.  I am fine to just
investigate on my own; I would guess you have other day time jobs like me.

I was JTAG stepping the vm7.S and the head{nommu|common}.S last night.  I
agree your explanation is the intent of the code, but my stm32f429-disco
board does NOT boot because the vector_table is in the .data section (which
is in SDRAM as you point out).  entry-v7m.S is setting VTOR and seems to be
taking SVCall BEFORE the data is copied from the flash to SDRAM (through
the code you explained in the previous email).  I think it makes sense that
my kernel startup code just goes off to a never-never land after making the
SVCall, and I was trying to figure out how to either place the vector_table
in the flash, or copy the data section to SDRAM BEFORE entry-v7m.

Of course, it is also possible that I am doing something wrong, but so far,
I had not made ANY change to my clone of the mainline kernel, which has the
stm32 config and the ARM v7M support.

Anyway, thanks much for your earlier emails.

**Comment by mcoquelin-stm32** [comment]
Ok,
I didn't understand that you were facing some crash with XIP image.

Of course I'm interested in what happens in your setup.
I don't know whether you are aware, but I created some wiki pages: http://elinux.org/STM32

I just tested  with today's afboot-stm32 HEAD from my github and with Kernel v4.4.
It works perfectly.

Comparing with my wiki page, can you see differences in your setup?
FYI, this is the version of my toolchain:
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20141119 (release) [ARM/embedded-4_9-branch revision 218278]
You can get it here: https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major

Could you try and see if you face different behaviour?
I didn't tested with GCC 5.2, but could have a try.

Regards,
Maxime

**Comment by henrychoi** [comment]
Thanks for the suggestion Maxime, I could not have gotten this far without
your STM32 wiki page in the first place.  I am a relative uClinux novice
who can easily make a mistake, and was surprised that the PC jumps to 0x0
(which is a reserved ROM address on stm32 as you know) after the
SVCall entry-v7m.S.
That is when I started looking into where the vector_table is.  I confirmed
in JTAG debug that the VTOR is setting set to 0x9000e400 (which is in SRAM
as you know).  Since this could all be due to my mistake, I don't want to
ask you to do any hard work; I first want to make sure that I am producing
the correct xipImage and vmlinux.

Since the kernel is booting for you, can you please do me just 1 favor:
send me a text file with the result of the following command:

arm-linux-readelf -A vmlinux > Maxime_vmlinux_readelf.txt

Thank you so much!

**Comment by henrychoi** [comment]
Actually Maxime, sorry for the SPAM but I just tried wiping the Buildroot
output folder and rebuilding, and got past the "SVC in SDRAM" problem.
Somehow, even though the register values are still pointing to the SDRAM
area, the uC did not hang on SVCall.

Now I am trying to run the init process, and the kernel is hanging
somewhere, and I wind up in unwind_frame() at unwind.c:449 somehow.  On
your STM32 wiki, you were not explicit about the rootfs.  Andreas Farbe
said in this year's Linux con presentation that he used romfs, but I didn't
find an information on how to prepare the romfs on your STM wiki.  So I
tried to link the initramfs into the kernel.  I am not sure if that is the
cause of the hang, but I will keep digging tomorrow.

Thanks for your hints; they were indispensable for my getting this close to
running Linux on stm32f4.

w/ regards,
Henry

**Comment by mcoquelin-stm32** [comment]
No problem Henry, you don't spam me.

I think I know your problem, there is a bug in Builroot regarding elf2flt, resulting in the entry point of the generated FLT files not to have the bit 0 set, whereas it should as it is Thumb code.

I have a for on my Github, which requires to use an external prebuilt toolchain (OSELAS).
This is not optimal as the toolchain is generated for Cortex-M3, and it is based on a lod GCC version (4.7 IIRC). Anyway, that is enough for me at the moment since I focus on Kernel side, I'm not looking after performance improvement for now.

With you toolchain, what you could try is to add a quick and dirty patch in FLT executable loading sequence in Kernel:

diff --git a/fs/binfmt_flat.c b/fs/binfmt_flat.c
index f723cd3..7c4a05b 100644
--- a/fs/binfmt_flat.c
+++ b/fs/binfmt_flat.c
@@ -912,7 +912,7 @@ static int load_flat_binary(struct linux_binprm *
         \* initialise library in order for us.  We are required to ca
         \* lib 1 first, then 2, ... and finally the main program (id 
         */
-       start_addr = libinfo.lib_list[0].entry;
- ```
    start_addr = libinfo.lib_list[0].entry | 1;
  ```
  
  #ifdef CONFIG_BINFMT_SHARED_FLAT
        for (i = MAX_SHARED_LIBS-1; i>0; i--) {

Regards,
Maxime

**Comment by mcoquelin-stm32** [comment]
Hmm sorry, looks like Github doesn't like diffs..

so in fs/binfmt_flat.c, juste replace:
start_addr = libinfo.lib_list[0].entry;
with:
start_addr = libinfo.lib_list[0].entry | 1;

**Comment by henrychoi** [comment]
Thank you for that hint Maxime, I just tried your recommendation, but still
have the same problem.  All this time, I've been loading the vmlinux (to
which the initramfs is linked by Buildroot; I know that xipImage probably
has this also, and am guessing the 2 are equivalent for running the kernel)
onto the flash by JTAG debugging from Eclipse (through ST-Link)  I've
checked that the initfamfs gets placed at the end of the .init.data
section, and gunzip decompress is being called in unpack_to_rootfs (one of
the initcall).  The start_thread(whose operation I don't fully understand)
seems to return for that flat_format. The problem seems to to be after
return from search_binary_handler()--somewhere around ret_from_fork.  I
thought vfork'ed child was supposed to run to completion, but I am just a
novice with this MMU-less scheme of things.  I hope I will begin to
understand by JTAG debugging some more.

BTW, I found Kamil Lulko's Buildroot fork
https://github.com/Varcain/buildroot_ARMv7M.git, to understand the
Buildroot fix required, but could not understand why he also patched HIS
kernel with YOUR "| 1" workaround for the start address, so I did not know
whether I should try his package/elf2flt/el2flt patch, ot his change to
disable PIC in busybox, and added R_ARM_THM_JUMP24 to elf2flt and uclibc.
I am not sure if this is the same Buildroot patch you were referring to...

**Comment by henrychoi** [comment]
Hello Maxime, can I possibly get your toolchain settings?  For example,
would the mainline kernel support uclibc-ng eabihf, and the VFPv4-D16?  I
turned on both these options in the Buildroot config.  I started wondering
about these these support while debugging the unexpected jump to
__invalid_entry after loading the /linuxrc initramfs (where I inserted your
"| 1" workaround) and starting the kernel thread for this init executable
(which is just busybox).  That stack trace is:

load_flat_binary() at binfmt_flat.c:915 0x806df5c

search_binary_handler() at exec.c:1,428 0x804f6e0 --> calls fmt->load_binary

exec_binprm() at exec.c:1,470 0x804f9d0

do_execveat_common() at exec.c:1,590 0x804f9d0

do_execve() at exec.c:1,634 0x804fad4

run_init_process() at main.c:911 0x8009282

kernel_init() at main.c:949 0x80c043a

ret_from_fork() at entry-common.S:118 0x8009a08 <-- MCU jumps to __invalid
shortly after this

I looked into the ret_from_fork, and chased the problem into ret_to_user()
being called from ret_from_fork() above.  ret_to_user uses this macro:

.macro v7m_exception_slow_exit ret_r0

cpsid i

ldr lr, =EXC_RET_THREADMODE_PROCESSSTACK

...

where the constant being loaded into LR is 0xfffffffd.  I saw that Emcraft
folks uses 0xffffffed in their entry-header.S, so looked up what that bit
[4] is.  The comment in v7m.h says: "If the processor implements the
FP extension
Bit [4] defines if the exception frame has space allocated for FP state
information, SBOP otherwise..."

So I tried modifying EXC_RET_THREADMODE_PROCESSSTACK to 0xffffffed, but got
saw the same problem.  I also tried to specify just eabi (instead of
eabihf) for the toolchain, and use the "software float" strategy in
Buildroot config, but still saw the same problem.

For tomorrow, I am thinking about just carefully diffing the latest
mainline kernel against the Emcraft kernel (which was forked off 2.6.33).
Of course any hint from you would change my plans.

w/ appreciation,

Henry

**Comment by henrychoi** [comment]
So I read up on how to return from an interrupt, and saw that 0xfffffffd is turning to the user thread, using PSP.  But when I checked the control register all the way up to there, it remains stuck at 1, which means we are ALWAYS using the MSP (indeed, the PSP remains at 0x0 all the way up to the offending bx lr that causes the usage fault to trigger).  So I tried changing EXC_RET_THREADMODE_PROCESSSTACK define to 0xfffffff9, and the CFSR (0xE000ED28) changed from UNSTKERR to IMPRECISERR instead, with BFAR (0xE000ED38) = 0xF8ED00E0--which doesn't seem to be a valid text address.

If the intention is for the kernel to use the PSP (process stack pointer), when does the switch from the MSP (which is the reset default) to the PSP take place?  So far, all the registers and code path before and after the ret_to_user seem identical. ..

**Comment by henrychoi** [comment]
After more debugging, I think lr = 0xfffffffd IS correct, since we DO want
to run the init code in user "space" (just the stack pointer really).
After the "bx lr", I confirmed that I land at pc = 0x90556040 (which is in
the SDRAM), which IS the address I modified (or'ing the 1 to the start
address) = 0x50556041.

The problem then appears to be that the busybox code is jumping to 0x0,
because of the content of the busybox image in SDRAM.

The memory dump of this neck of the woods is:

0x90556040 : 0x90556040 <Hex>
  Address   0 - 3     4 - 7     8 - B     C - F
  90556040  00000000  0448054B  1B1A062B  02D9044B
  90556050  03B11847  704700BF  08010000  0B010000
  90556060  00000000  05480649  091A8910  022391FB

There are 2 things I don't understand here:
1. The immediate problem seems to be that the content of 0x90556060 is
   0x0, so the program is jumping off to the uC's ROM.
2. Why is the lr = 0?  Is that normal for a statically linked BFLT exe?
   Am I missing some patch for the busybox?  I've never debugged an init
   program--not to mention a BFLT binary.  Looks like yet another hill to
   climb...

BRm4/output/build/busybox-1.24.1$ file busybox
busybox: BFLT executable - version 4 gotpic

I wonder if the copying of the initramfs from the init.data in flash to
SDRAM is working correctly, or whether there is some kind of cacheing being
done inside the SDRAM chip?

**Comment by henrychoi** [comment]
Looking into why my busybox BFLT image looks like garbage in the SDRAM, I looked at the busybox exe more carefully, and was shocked at how small it was: 300 BYTES??

BRm4/output/build/busybox-1.24.1$ ~/band/uClinux/bflt-utils/readbflt/readbflt busybox

Readbflt v0.1
Copyright (c) 2012, Tactical Network Solutions, Craig Heffner cheffner@tacnetsol.com
Rev:            4
Flags:          GOTPIC [0x02]
File size:      0x00000154
Stack Size:     0x00003E80
Reloc Count:    2
Reloc Start:    0x0000014C
Build date:     0x569A7CD3

bFLT Sections:
                .text    0x00000040 - 0x00000100
                .data    0x00000100 - 0x0000014C
                .bss     0x0000014C - 0x00000170

**Comment by henrychoi** [comment]
Well I found out that the problem is that Buildroot build for busybox is actually failing that the final step (link), because of the "-elf2flt" specified to the $(CC)--which interprets the option as the entry point.  Since you want to focus on the kernel, this is not your problem.  I don't know how to reach the Buildroot people.  I know [this change](http://buildroot-busybox.2317881.n4.nabble.com/git-commit-nommu-flat-build-packages-with-the-correct-FLAGS-td51272.html) was introduced a couple of years ago, and some people ran into this problem before me, but [the discussion](http://search.gmane.org/?query=cannot+find+entry+symbol+lf2flt%3B+defaulting+to&author=&group=gmane.comp.lib.uclibc.buildroot&sort=relevance&DEFAULTOP=and&xP=Zcannot%09Zfind%09Zentri%09Zsymbol%09Zlf2flt%09Zdefault&xFILTERS=Gcomp.lib.uclibc.buildroot---A) did not have a conclusion.

I am just trying to work around the problem for now.

**Comment by mcoquelin-stm32** [comment]
Ok, it looks to be the issue I told you about 1 week ago regarding elf2flt.
You should be able to use the workaround I proposed in the Kernel.

Regards,
Maxime

**Comment by henrychoi** [comment]
Thanks for the reply, Maxime.
I HAVE BEEN using your kernel workaround ever since you told me.  Like I
said, it's because the cross gcc built by Buildroot does not understand
"-elf2flt" argument.  It's possible that the cross LD understands it, but
busybox invokes CC instead of LD to link.  That's when the cross CC barfs
about not being able to find the entry point "lf2flt" (because it
interprets "-e" as the entry point argument).  I worked around by replacing
"-elf2flt" with "-Wl,-elf2flt" in busybox Makefile.  After that, the
busybox BFLT is now 450 KB instead of 300 B.

But right after that I got stuck at where the kernel is loading the BFLT
executable.  It look like there is something wrong with the busybox flat
binary, because the kernel is picking up an id of 0x7F for the GOTPIC
section of the executable (the first part of the binary I think).  I have
no choice but to dig into the BFLT format, and looking at the busybox
binary produced.  Last night I tried varcain's busybox patch to comment out
the PIC options from the compiler, but that didn't make any difference.

So far, running mainline Linux on my stm32f429-disco is turning out to be a
lot more work than I guessed, but I still think I am going to win my bet
about being able to run a wearable FW on uClinux in the end.

**Comment by henrychoi** [comment]
Hi Maxime, I read [this explanation](https://docs.blackfin.uclinux.org/doku.php?id=toolchain:creating_libraries) of flat shared executable format, and thought there is a problem in the fact that kernel stm32_defconfig specifies CONFIG_BINFMT_SHARED_FLAT (which uses ID), but Buildroot does NOT specify shared flat (in fact, gcc does not even compile for the shared flat option).  But what confuses me when I check varcain's Buildroot is that even though his kernel config and Buildroot toolchain options for the binfmt and binfmt_shared is the same as mine, he apparently emits busybox exe with NO GOTPIC (the exe flag is 0x1, which means RAM).

I am going to look into the apparent discrepancy, but do you know whether the following gcc flags that are picked up by BBR2_BINFMT_FLAT_SHARED are compatible with the kernel CONFIG_BINFMT_SHARED_FLAT (which is in the mainline stm32_defconfig)?

ifeq ($(BR2_BINFMT_FLAT_SHARED),y)
TARGET_LDFLAGS += -mid-shared-library -mshared-library-id=0
TARGET_CFLAGS += -mid-shared-library -mshared-library-id=0
TARGET_CXXFLAGS += -mid-shared-library -mshared-library-id=0
endif

**Comment by henrychoi** [comment]
After getting a little farther by faithfully copying varcain's uclibc defconfig, I am still puzzled at why the mainline stm32 kernel turned on BINFMT_SHARED_FLAT.  The bin format config for toolchain, uclibc, and kernel are inconsistent in the mainline
- toolchain (buildroot gcc): BINFMT_FLAT
- uclibc: BINFMT_FLAT
- kernel: BINFMT_SHARED_FLAT

After staring at why cross gcc won't build for BINFMT_SHARED_FLAT, I realized that 'man gcc' lists -mid-shared-library is a blackfin specific option, and NOT listed for arm--it would appear that gcc still does NOT support this option, so uclibc cannot turn it on either.  So is there a value in still turning on BINFMT_SHARED_FLAT?  Right now I am trying to run with just BINFMT_FLAT, and see how far I get...
